python augment_maf.py -n /Volumes/Shared/projects/arizona_samples/Exome-bam/444-Blood-s_7_TTAGGC_paired.dup.sorted.bam -t /Volumes/Shared/projects/arizona_samples/Exome-bam/444-T2-s_8_ACTTGA_paired.dup.sorted.bam -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444-T1vst2-passed-somatic-snvs+indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444-T2vst1-passed-somatic-snvs+indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444Z1-passed-somatic.snvs.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444z1-passed-somatic.indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444z2-passed-somatic-indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444z2-passed-somatic-snvs.maf /Volumes/Shared/reference/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa /Volumes/Shared/projects/arizona_samples/Exome-maf/444-T2-augumented.maf

python augment_maf.py -n /Volumes/Shared/projects/arizona_samples/Exome-bam/444-Blood-s_7_TTAGGC_paired.dup.sorted.bam -t /Volumes/Shared/projects/arizona_samples/Exome-bam/444-T1-s_8_CAGATC_paired.dup.sorted.bam -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444-T1vst2-passed-somatic-snvs+indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444-T2vst1-passed-somatic-snvs+indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444Z1-passed-somatic.snvs.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444z1-passed-somatic.indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444z2-passed-somatic-indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/444z2-passed-somatic-snvs.maf /Volumes/Shared/reference/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa /Volumes/Shared/projects/arizona_samples/Exome-maf/444-T1-augumented.maf

python augment_maf.py -n /Volumes/Shared/projects/arizona_samples/Exome-bam/111-Blood-s_7_CGATGT_paired.dup.sorted.bam -t /Volumes/Shared/projects/arizona_samples/Exome-bam/111-T1-s_8_ACAGTG_paired.dup.sorted.bam -m /Volumes/Shared/projects/arizona_samples/Exome-maf/111-T2vst1-passed-somatic-snvs+indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/111z1.passed.somatic.snvs.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/111z2-passed-somatic-indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/111z2-passed.somatic.snvs.maf /Volumes/Shared/reference/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa /Volumes/Shared/projects/arizona_samples/Exome-maf/111-T1-augumented.maf



python augment_maf.py -n /Volumes/Shared/projects/arizona_samples/Exome-bam/111-Blood-s_7_CGATGT_paired.dup.sorted.bam -t /Volumes/Shared/projects/arizona_samples/Exome-bam/111-T2-s_8_GCCAAT_paired.dup.sorted.bam -m /Volumes/Shared/projects/arizona_samples/Exome-maf/111-T1vst2-passed-somatic-snvs+indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/111-T2vst1-passed-somatic-snvs+indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/111z1.passed.somatic.snvs.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/111z2-passed-somatic-indels.maf -m /Volumes/Shared/projects/arizona_samples/Exome-maf/111z2-passed.somatic.snvs.maf /Volumes/Shared/reference/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa /Volumes/Shared/projects/arizona_samples/Exome-maf/111-T2-augumented.maf


